<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>MicroluxErgConnect</AssemblyName>
    <RootNamespace>MicroluxErgConnect</RootNamespace>
    <AssemblyVersion>1.0.0.4</AssemblyVersion>
    <FileVersion>1.0.0.4</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Autoupdater.NET.Official" Version="1.8.3" />
    <PackageReference Include="QuestPDF" Version="2024.3.0" />
    <PackageReference Include="System.IO.Ports" Version="9.0.9" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="../Shared/ILog.cs" Link="Logging/ILog.cs" />
    <Compile Include="../Shared/Erg/ErgDataModels.cs" Link="Erg/ErgDataModels.cs" />
    <Compile Include="../Shared/Erg/ErgDataParser.cs" Link="Erg/ErgDataParser.cs" />
    <Compile Include="../Shared/Erg/ErgDataSerializer.cs" Link="Erg/ErgDataSerializer.cs" />
    <Compile Include="../Shared/Erg/ErgReportBuilder.cs" Link="Erg/ErgReportBuilder.cs" />
  </ItemGroup>
</Project>
