<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>MicroluxErgConnect</AssemblyName>
    <RootNamespace>MicroluxErgConnect</RootNamespace>
    <AssemblyVersion>1.0.0.1</AssemblyVersion>
    <FileVersion>1.0.0.1</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="QuestPDF" Version="2024.3.0" />
    <PackageReference Include="System.IO.Ports" Version="9.0.9" />
  </ItemGroup>
</Project>
